# Generated by Django 4.2.7 on 2023-12-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polka', '0009_person_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polka.book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polka.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='books2',
            field=models.ManyToManyField(related_name='booknew', through='polka.CartItem', to='polka.book'),
        ),
    ]
